# yaml-language-server: $schema=https://raw.githubusercontent.com/francescozoccheddu/pidby/main/schema/config.json
layout: "a4"
pageFiles:
  - "/pages/page-1.pug"
  - "pages/page-2.ejs"
  - "pages/page-3.html"
