env:
  browser: false
  es2021: true
  node: true
root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:import/recommended
  - plugin:import/typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: true
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
plugins:
  - "@typescript-eslint"
  - no-relative-import-paths
  - import
  - unused-imports
  - simple-import-sort
overrides:
  - files:
      - "*.ts"
    extends:
      - "plugin:@typescript-eslint/recommended"
      - "plugin:@typescript-eslint/recommended-type-checked"
    parserOptions:
      project: "./tsconfig.json"
rules:
  no-relative-import-paths/no-relative-import-paths:
    - error
    - rootDir: "./src"
      prefix: "pidby"
  indent:
    - error
    - 2
    - SwitchCase: 1
  simple-import-sort/imports:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  import/no-default-export:
    - error
  "@typescript-eslint/no-unused-vars":
    - "off"
  "@typescript-eslint/member-delimiter-style":
    - error
  no-multiple-empty-lines:
    - error
    - max: 1
  no-trailing-spaces:
    - error
  comma-dangle:
    - error
    - always-multiline
  import/default:
    - "off"
  unused-imports/no-unused-imports:
    - error
  "@typescript-eslint/explicit-function-return-type":
    - error
  "@typescript-eslint/ban-types":
    - error
    - types:
        "String":
          "fixWith": "Str"
        "string":
          "fixWith": "Str"
        "boolean":
          "fixWith": "Bool"
        "Number":
          "fixWith": "Num"
        "number":
          "fixWith": "Num"
        "unknown":
          "fixWith": "Unk"
        "undefined":
          "fixWith": "Und"
        "null":
          "fixWith": "Nul"
        "Symbol":
          "fixWith": "Sym"
        "symbol":
          "fixWith": "Sym"
        "Array":
          "fixWith": "Arr"
      extendDefaults: true
